Add a unit test for dyn bgd hotpix imposter calc
sot/starcheck pull request #418
Opened 2023-07-10 18:56 UTC by jeanconn

## Description
Add a unit test for dyn bgd hotpix imposter calc.  Maybe it is a bridge too far for the #412 PR, but we could start to accumulate Python unit tests here as we go.  This is not a particularly clean unit test; I suppose it would be better to ask sparkles what we want for dyn_bgd_n_faint and dyn_bgd_dt_ccd or some such?  But this does work as a functional test for the imposter calc.

This addresses the issue at the end of #412 that the functional testing of the imposter calculation was not demonstrated.

## Interface impacts

## Testing

I tested this with install testing into my ska3-matlab-2023.4rc6 environment.

### Unit tests

- [x] Mac

Independent check of unit tests by [REVIEWER NAME]
- [ ] [PLATFORM]:

### Functional tests

No functional testing.

2023-07-10 18:59 UTC, jeanconn commented
@taldcroft I don't know if we actually want to merge this or something like it, but it seemed a reasonable way to document what I did for functional test.

2023-07-11 10:03 UTC, taldcroft requested changes
This looks great! There was only one real issue with using `>=` or `<=` instead of splitting to `>` and `==`. Then I saw an opportunity to simplify the code and started typing.

2023-07-11 10:03 UTC, taldcroft commented on starcheck/tests/test_utils.py
> +        assert imposter["t_ccd"] == t_ccd
Move this into the main checking loop.
```suggestion
```

2023-07-11 11:56 UTC, jeanconn commented
OK.  Thanks.  I just committed your changes and re-ran the test successfully.

2023-07-11 11:57 UTC, jeanconn commented
This is a PR _against_ #412, so my preference would be to get #412 approved without this, get this approved, and then merge them both.

2023-07-11 12:20 UTC, taldcroft approved these changes
Looks good now. I ran the test and got a pass. Not required, but probably worth cleaning up these warnings by preceding the regex string with `r`.
```
============================================= warnings summary ==============================================
starcheck/pcad_att_check.py:51
  /Users/aldcroft/git/starcheck/starcheck/pcad_att_check.py:51: DeprecationWarning: invalid escape sequence '\d'
    match = re.match('^(\d+\.\d+)\s+\|\s+(\S+)\s*$',

starcheck/pcad_att_check.py:67
  /Users/aldcroft/git/starcheck/starcheck/pcad_att_check.py:67: DeprecationWarning: invalid escape sequence '\d'
    match = re.match('^(\d+\.\d+)\s+\|\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s*', line)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

2023-07-11 15:07 UTC, merged